language: python
python: '2.7'
install: pip install -r requirements.txt
script:
- mkdir dist
- tar cvf dist/corkboard-${TRAVIS_TAG}.tar.gz .
skip_cleanup: true
deploy:
  branch: master
  provider: releases
  api_key:
    secure: arjXESFzVPFPurVQqTpamg8Ca7gedLa06rWvElt9mmAVYi54qaVseUkqwGFjbKuLqtiOXOnWDbKzMKkX+fayfl/zQawpqCiHeSP2zdbRjLtQJN/rUmssfQaXQOzFbKxf9XHP+ZGVgduMwDdmfgsbOiW088yGk6gGbkTscqdmaCk=
  on:
    tags: true
  name: ${TRAVIS_TAG}
  prelease: true
