language: "python"
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

install: "pip install -r requirements.txt"
script: 
    - "cd corkboard/corkboard && mv secrets.py.ex secrets.py"
    - "python corkboard/manage.py test"
